# Generated by Django 2.1.2 on 2018-10-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('createDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
