# Generated by Django 2.1.2 on 2018-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
